site_name: lbpqc - docs

repo_url: https://github.com/mikolajlh/lbpqc
repo_name: mikolajlh/lbpqc
edit_uri: blob/main/docs/

nav:
  - Home: "index.md"
  - Examples:
      - examples/attacking_congruential_pkc.ipynb
      - examples/attacking_discrete_knapsack_pkc.ipynb
      - examples/constructing_and_attacking_GGH_pkc.ipynb
      - examples/constructing_and_attacking_NTRU_pkc.ipynb
  - Modules:
      - Primitives: primitives.md
validation:
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn
theme:
  name: material
  icon:
    logo: material/shield-key
  font:
    text: Lato
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

watch:
  - src/lbpqc

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - markdown.extensions.tables
  - markdown.extensions.codehilite
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [./src]
          options:
            show_root_heading: true
