name: CI/CD
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        permissions:
            contents: write
        
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install flake8 pytest
                pip install .
            - name: Lint with flake8
              run: |
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Test with pytest
              run: |
                pytest
    build_mkdocs:
        needs: build
        permissions:
            contents: write
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with: 
                python-version: '3.11'
            - run: pip install mkdocs mkdocs-material mkdocstrings-python mkdocs-jupyter
            - run: mkdocs build --strict
            - run: mkdocs gh-deploy --force

    deploy_mkdocs:
        needs: build_mkdocs
        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                ref: gh-pages
            - uses: actions/configure-pages@v5
            - uses: actions/upload-pages-artifact@v3
              with:
                path: '.'
            - id: deployment
              uses: actions/deploy-pages@v4